-- MySQL Script generated by MySQL Workbench
-- Ср. 27 апр. 2016 05:51:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gb_calendar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gb_calendar` ;

-- -----------------------------------------------------
-- Schema gb_calendar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gb_calendar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `gb_calendar` ;

-- -----------------------------------------------------
-- Table `gb_calendar`.`gb_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gb_calendar`.`gb_request` ;

CREATE TABLE IF NOT EXISTS `gb_calendar`.`gb_request` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  `address` VARCHAR(255) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `phone` VARCHAR(10) NOT NULL COMMENT '',
  `date_create` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
